// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace demoapplication.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260227050609_e1")]
    partial class e1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("demoapplication.Model.AttendanceRecord", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("HoursWorked")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AttendanceId");

                    b.HasIndex("EmployeeId", "AttendanceDate")
                        .IsUnique();

                    b.ToTable("AttendanceRecords");

                    b.HasData(
                        new
                        {
                            AttendanceId = 1,
                            AttendanceDate = new DateTime(2026, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            HoursWorked = 8.5m,
                            Status = "Present"
                        },
                        new
                        {
                            AttendanceId = 2,
                            AttendanceDate = new DateTime(2026, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 2,
                            HoursWorked = 6.5m,
                            Status = "ShortHours"
                        },
                        new
                        {
                            AttendanceId = 3,
                            AttendanceDate = new DateTime(2026, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 3,
                            HoursWorked = 0m,
                            Status = "Absent"
                        },
                        new
                        {
                            AttendanceId = 4,
                            AttendanceDate = new DateTime(2026, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 4,
                            HoursWorked = 8m,
                            Status = "ShortHours"
                        },
                        new
                        {
                            AttendanceId = 5,
                            AttendanceDate = new DateTime(2026, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 5,
                            HoursWorked = 7.5m,
                            Status = "Present"
                        });
                });

            modelBuilder.Entity("demoapplication.Model.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PolicyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Email = "ayush@mx.com",
                            FirstName = "Ayush",
                            IsActive = true,
                            LastName = "Sarvaiya",
                            PolicyId = 1
                        },
                        new
                        {
                            EmployeeId = 2,
                            Email = "hasti@mx.com",
                            FirstName = "Hasti",
                            IsActive = true,
                            LastName = "Movaliya",
                            PolicyId = 2
                        },
                        new
                        {
                            EmployeeId = 3,
                            Email = "hatim@mx.com",
                            FirstName = "Hatim",
                            IsActive = true,
                            LastName = "Chharchhoda",
                            PolicyId = 1
                        },
                        new
                        {
                            EmployeeId = 4,
                            Email = "srishti@mx.com",
                            FirstName = "Srishti",
                            IsActive = true,
                            LastName = "Singh",
                            PolicyId = 3
                        },
                        new
                        {
                            EmployeeId = 5,
                            Email = "veer@mx.com",
                            FirstName = "Veer",
                            IsActive = true,
                            LastName = "Vora",
                            PolicyId = 2
                        });
                });

            modelBuilder.Entity("demoapplication.Model.Policy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyId"));

                    b.Property<decimal>("MinDailyHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PolicyId");

                    b.ToTable("Policies");

                    b.HasData(
                        new
                        {
                            PolicyId = 1,
                            MinDailyHours = 8m,
                            Name = "Policy1 8 Hours"
                        },
                        new
                        {
                            PolicyId = 2,
                            MinDailyHours = 7.5m,
                            Name = "Policy2 7.5 Hours"
                        },
                        new
                        {
                            PolicyId = 3,
                            MinDailyHours = 9m,
                            Name = "Policy3 9 Hours"
                        });
                });

            modelBuilder.Entity("demoapplication.Model.AttendanceRecord", b =>
                {
                    b.HasOne("demoapplication.Model.Employee", "Employee")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("demoapplication.Model.Employee", b =>
                {
                    b.HasOne("demoapplication.Model.Policy", "Policy")
                        .WithMany("Employees")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("demoapplication.Model.Employee", b =>
                {
                    b.Navigation("AttendanceRecords");
                });

            modelBuilder.Entity("demoapplication.Model.Policy", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
